### ISSUE TITLE
do you have any plans to improve this app

### ISSUE THREAD

**Issue by zhuoqinyue** [Dav1d-Fn/Fliq-Desktop-Flipclock#1]
I like the fliplo on mac.
fliplo can work on the lock screen, and it look so cool.

do you have any plans to implement this features

**Comment by Dav1d-Fn** [comment]
Thank you for your feedback. Currently, I am using the project as it is, but I do have plans to improve it in the future. If any specific needs arise, I will certainly address them. However, I do not have any plans to add a lock screen feature, as there are many existing solutions available.

**Comment by zhuoqinyue** [comment]
could you share some solutions?

**Comment by Dav1d-Fn** [comment]
I currently don't use any screensavers. I'm not entirely sure if creating a screensaver with Tauri would be straightforward. However, have you considered using Fliplo? It might be a good alternative.
